apiVersion: v1
kind: Service
metadata:
  name: fakenews-service
spec:
  type: NodePort
  selector:
    app: fakenews
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30036
